package quickstart;

import java.sql.SQLException;
import java.util.List;

import pm.pride.*;

/**
 * @author jlessner
 */
public class Customer extends MappedObject implements Cloneable, java.io.Serializable {
    public static final String TABLE = "CUSTOMER";
    public static final String COL_ID = "id";
    public static final String COL_NAME = "name";
    public static final String COL_FIRST_NAME = "first_name";

    protected static final RecordDescriptor red =
        new RecordDescriptor(Customer.class, TABLE, null)
            .row( COL_ID,   "getId",   "setId" )
            .row( COL_NAME,   "getName",   "setName" )
            .row( COL_FIRST_NAME,   "getFirstName",   "setFirstName" );

    public RecordDescriptor getDescriptor() { return red; }

    private static String[] keyFields = new String[] { "id" };
    public String[] getKeyFields() { return keyFields; }

    private int id;
    private String name;
    private String firstName;

    // Read access functions
    public int getId()   { return id; }
    public String getName()   { return name; }
    public String getFirstName()   { return firstName; }

    // Write access functions
    public void setId(int id) { this.id = id; }
    public void setName(String name) { this.name = name; }
    public void setFirstName(String firstName) { this.firstName = firstName; }


    // Reconstructor
    public Customer(int id) throws SQLException {
        setId(id);
        findx();
    }

    /** Self-made convenience constructor, not generated by the entity generator */
    public Customer(int id, String name, String firstName) throws SQLException {
    	this.id = id;
    	this.name = name;
    	this.firstName = firstName;
    	create();
    }
    
    public Customer() {}

    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    public String toString() {
    	return id + ": " + name + ", " + firstName;    	
    }
    
}

